### ISSUE TITLE
Samplers with different type have binding to zero while initializing

### ISSUE THREAD

**Issue by bluekyu** [bluekyu/render_pipeline_cpp#12]
# Panda3D & Render Pipeline
- https://www.panda3d.org/forums/viewtopic.php?f=2&t=19723
- https://github.com/tobspr/RenderPipeline/issues/80

# OpenGL issues
- https://www.opengl.org/discussion_boards/showthread.php/176366-Samplers-of-different-types-use-the-same-textur
- https://www.opengl.org/discussion_boards/showthread.php/173641-Default-values-for-samplers
- https://www.khronos.org/opengl/wiki/Sampler_(GLSL)#Binding_textures_to_samplers

# OpenGL Refs
- https://www.khronos.org/opengl/wiki/Layout_Qualifier_(GLSL)
- https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glValidateProgram.xhtml

# Solution
1. Do glValidateProgram after GL states is ready.
   - However, glValidateProgram cause performance degradation while rendering.
2. Use `layout(binding)`

**Comment by tobspr** [comment]
Sorry for replying lately, somehow I must have missed this Issue notification ...

So you mean the issue is, that during initialization the uniforms are not set? Or do I misunderstand that

**Comment by bluekyu** [comment]
My issue thread is hints that I searched, previously.
But I could not test those because I didn't have AMD card.

The first changes the point of calling glValidateProgram function in
Panda3D to after binding all GL states.
(glValidateProgram is called when the shader program is built.)
However, this causes performance degradation.

The second changes binding point (default 0) of uniform to another point in
shader.
Type of "IESDatasetTex" uniform is sampler3D, but 0-binding point may not
be sampler3D before initializing (when building shader).
I guess that AMD detects this error, but NVIDIA does not.


2018-03-05 22:05 GMT+09:00 tobspr <notifications@github.com>:

**Comment by bluekyu** [comment]
I guess that Intel OR AMD compiler cannot optimize if IESDatasetTex sampler is used, or not.
